KS-3-4 make a solution of the task 4 of the lesson 3
yauheni-lebedzeu/kotlin-sprint pull request #14
Opened 2024-12-09 21:03 UTC by yauheni-lebedzeu

2024-12-10 19:14 UTC, ievetrovdev requested changes

2024-12-10 19:14 UTC, ievetrovdev commented on src/main/kotlin/lesson_3/lesson_3_task_4.kt
Обращаю внимание на пример строки для отправки на сервер [откуда-куда;номер хода]
В условии не случайно уточнен выводимый формат. Если формат готовой строки будет отличаться, то сервер не сможет ее распарсить и программа может упасть/не работать итд.
Предлагаю привести формат в соответствие с форматов в ТЗ)

2024-12-11 07:07 UTC, SenlaCoursesAdmin commented on src/main/kotlin/lesson_3/lesson_3_task_4.kt
Аааа, пробел))

2024-12-11 07:07 UTC, yauheni-lebedzeu commented on src/main/kotlin/lesson_3/lesson_3_task_4.kt
Аааа, пробел)))

2024-12-11 18:11 UTC, ievetrovdev approved these changes
Теперь все верно, отлично!

2024-12-11 20:43 UTC, merged