KS-4-2 make a solution of the task 2 of the lesson 4
yauheni-lebedzeu/kotlin-sprint pull request #17
Opened 2024-12-11 07:58 UTC by yauheni-lebedzeu

2024-12-11 13:07 UTC, ievetrovdev requested changes

2024-12-11 13:07 UTC, ievetrovdev commented on src/main/kotlin/lesson_4/lesson_4_task_2.kt
> +    val maxWeight = 100
В предыдущем задании сделал полноценные константы, почему здесь просто неизменяемые переменные. Давай тоже в константы переведем

2024-12-11 13:09 UTC, yauheni-lebedzeu commented on src/main/kotlin/lesson_4/lesson_4_task_2.kt
> +    val maxWeight = 100
Без проблем. Просто решил, что эти значения могут меняться)

2024-12-12 06:56 UTC, ievetrovdev approved these changes
Так то да, но нужно исходить из ТЗ, по которому они не меняются)

2024-12-12 07:28 UTC, merged