KS-4-4 make a solution of the task 4 of the lesson 4
yauheni-lebedzeu/kotlin-sprint pull request #19
Opened 2024-12-11 21:11 UTC by yauheni-lebedzeu

2024-12-12 07:10 UTC, ievetrovdev requested changes

2024-12-12 07:10 UTC, ievetrovdev commented on src/main/kotlin/lesson_4/lesson_4_task_4.kt
> +    val isUnevenTraining = trainingDayNumber % 2 > 0
По новому нечетность нашел, обычно пишут != 0) 
Вообще можно находить только четность и применять его уже при выводе “как есть” или с отрицанием (инвертируя значение).

2024-12-12 09:27 UTC, yauheni-lebedzeu commented on src/main/kotlin/lesson_4/lesson_4_task_4.kt
> +    val isUnevenTraining = trainingDayNumber % 2 > 0
А, ну да, логично)

2024-12-13 06:30 UTC, ievetrovdev approved these changes

2024-12-13 06:30 UTC, ievetrovdev commented on src/main/kotlin/lesson_4/lesson_4_task_4.kt
> +        Упражнения для рук:    $isUnevenTraining
Хорошо, но можно было сразу при выводе инвертировать

2024-12-13 07:06 UTC, merged