KS-5-1 make a solution of the task 1 of the lesson 5
yauheni-lebedzeu/kotlin-sprint pull request #21
Opened 2024-12-12 09:25 UTC by yauheni-lebedzeu

2024-12-12 17:43 UTC, ievetrovdev requested changes

2024-12-12 17:43 UTC, ievetrovdev commented on src/main/kotlin/lesson_5/lesson_5_task_1.kt
> +    val firsRandomInteger = Random.nextInt(UPPER_BOUND_OF_SUMMANDS)
Любой импорт – лишний код в классе. Неиспользуемый импорт – неиспользуемый код. Существуют условно тонкие материи, когда надо использовать какую-то конкретную реализацию под капотом. Поэтому обоснованно может быть вызвать некую альтернативу из Котлин или похожий функционал, но с другим внутренним алгоритмом из Джавы. Ситуативно. Здесь я бы использовал экстеншн получения рандомного числа из диапазона: (1..10).random()

2024-12-12 19:45 UTC, yauheni-lebedzeu commented on src/main/kotlin/lesson_5/lesson_5_task_1.kt
> +    val firsRandomInteger = Random.nextInt(UPPER_BOUND_OF_SUMMANDS)
Ага, понял. Сейчас поправим)

2024-12-13 19:30 UTC, ievetrovdev approved these changes

2024-12-13 20:54 UTC, merged